name: 01 Primeiro CI

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - 'README.md'
  
  workflow_dispatch:

jobs:
  primeiro-job:
    runs-on: ubuntu-latest

    steps:
      - name: Meu nome e RA
        run: echo "Diego Alves - RA 6324649"
      - name: Mostra o diretório de trabalho
        run: pwd
      - name: Nome do repo
        run: echo ${{ github.repository }}