name: 01 Primeiro CI

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - 'README.md'
  
  workflow_dispatch:

jobs:
  primeiro-job:
    runs-on: ubuntu-latest

    steps:
      - name: Imprime uma mensagem
        run: echo "bom dia"
      - name: Mostra o diretório de trabalho
        run: pwd
      - name: Lista os arquivos do diretório
        run: ls ~ -a